sudo: false

branches:
  only:
  - master
  - "/v\\d+\\.\\d+\\.*/"

git:
  submodules: false

before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- pwd
- ls -lh
- ls -lh ./*

install:
- export MALARIAGEN_BINDER_HOME=~/opt
- "./binder/install-texlive.sh"

cache:
  timeout: 1000
  directories:
  - "~/opt"

script:
- source binder/env.sh
- "./build.sh introduction"
- "./build.sh chapter1"
- "./build.sh chapter2"
- "./build.sh chapter3"
- "./build.sh chapter4"
- "./build.sh chapter5"
- "./build.sh discussion"

deploy:
  provider: releases
  api_key:
    secure: Jd9kIqzbHUZ9Pdub3QORhJfZvhFfiCL2CZV50bwfkr4CZRiBC7Jiq2kuPPMANxCQpKzfw9cc92NtVP/sd2hTzNA7xVXFnSwOXLhuSszE/ztEivmW/fArDY+JX5m/KuZqtBJBrJpww4jRmPn98oereHvfT2xlVTfL48KbhOc/5a10McZi3Mobbs/VIMG+SQi7XJBLgCcsQYhxG8PNnm4LU3/JUUu/2C7U2xxeOyyfDB0LKZD8HYLoaVjv0oN4MsPtsNAod1sVQaZbrlF1ygtJeCGcE9nCuG2d8Ie6R9ZZTdMtCMfQ+pJlcC8lZEzGsjk/aBHRUEFYy9uCp/voG/QBKqT/H4WTA5iXk3VD+7YE97jq623gCQcHepGlm0/ScigRf/sIwNmqT46Brj5aa5gbcK0S7rFM3PWOvMSA/AmU9uT30LEwyeYavTZsA5njB8dKSzqbsnhkw9Y47Y+Q2ikJoaDWrSPpH0ZCTElI12WLzAiHeaS3bCPykUh6AdXJXeoOlCqEWXnZcpYQ4+bTwAq4bA5/A3BRBZvHrDC7IYfo6aMS1BP0Qo/v9r8RTqBrKKZ4vtEaHsFmNRVEXMSH2pQqnH//xR1VBqMGqCM4gFL31P7A3j8c5OM1px2i2XnFaq55ldc+am5XwzWMeAD1UU7y8B9x9h2gm8giSBWEfLJh2IQ=
  file: 
    - build/introduction.pdf
    - build/chapter1.pdf
    - build/chapter2.pdf
    - build/chapter3.pdf
    - build/chapter4.pdf
    - build/chapter5.pdf
    - build/discussion.pdf
  skip_cleanup: true
  on:
    repo: alimanfoo/dphil
    tags: true
